runtime: nodejs20
service: frontend

env_variables:
  NEXT_PUBLIC_API_URL: "https://proyeckev.uc.r.appspot.com"

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /static
    static_dir: public
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|json|svg))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|ico|txt|json|svg)$
    secure: always

  - url: /.*
    script: auto
    secure: always

entrypoint: node .next/standalone/server.js

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env: standard 